name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      # Build Frontend Docker Image
      - name: Build Frontend Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mearn-stack_frontend mern-docker/frontend
      
      - name: Setup .env file for Backend
        run: |
          touch backend/.env | echo PORT=${{vars.PORT}} >> backend/.env | echo MONGO_STR=${{secrets.MONGO_STR}} >> backend/.env
          cat backend/.env
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend backend
          
      # Build Backend Docker Image
      - name: Build Backend Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mearn-stack_backend mern-docker/backend

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Push Frontend Docker Image to Docker Hub
      - name: Push Frontend Docker Image
        run: docker push stt96/mearn-stack_frontend:latest
      
      # Push Backend Docker Image to Docker Hub
      - name: Push Backend Docker Image
        run: docker push stt96/mearn-stack_backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # SSH into Server instance and deploy
      - name: SSH into Server instance and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          
          script: |
            # Stop and remove existing containers
            docker stop mearn-stack_frontend || true
            docker rm -f mearn-stack_frontend || true
            docker stop mearn-stack_backend || true
            docker rm -f mearn-stack_backend || true
            
            # Pull latest images from Docker Hub
            docker pull stt96/mearn-stack_frontend:latest
            docker pull stt96/mearn-stack_backend:latest

            # Prune unused Docker resources
            docker system prune -f

            # Run containers with port mapping
            # docker run -d -p 5174:4000 --name mearn-stack_appew ${{ secrets.DOCKER_USERNAME }}/mearn-stack_appew:latest
            # 5174 is the port of the host machine, 4000 is the port of the container
            docker run -d -p 8000:8000 --name mearn-stack_backend ${{ secrets.DOCKER_USERNAME }}/mearn-stack_backend:latest
            docker run -d -p 5173:5173 --name mearn-stack_frontend ${{ secrets.DOCKER_USERNAME }}/mearn-stack_frontend:latest
